version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    env_file:
     - pgadmin.env
    ports: 
      - 5050:80
  db:
    image: postgres
    env_file: 
     - postgresql.env
    ports: 
     - 5432:5432
    depends_on: 
     - pgadmin