spring:
  datasource:
    password: development
    url: jdbc:postgresql://localhost:5432/pressao
    username: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
    show-sql: true
  liquibase:
    enabled: true
